import type { CategoryMeta, CategoryKey, Message } from "@/features/category/types";

export const CATEGORIES: CategoryMeta[] = [
  { key: "orders",    label: "Orders",    count: 14, color: "text-green-700 dark:text-green-400",   bg: "bg-green-50 dark:bg-green-950" },
  { key: "payments",  label: "Payments",  count: 9,  color: "text-purple-700 dark:text-purple-400", bg: "bg-purple-50 dark:bg-purple-950" },
  { key: "inventory", label: "Inventory", count: 11, color: "text-blue-700 dark:text-blue-400",     bg: "bg-blue-50 dark:bg-blue-950" },
  { key: "logistics", label: "Logistics", count: 7,  color: "text-orange-700 dark:text-orange-400", bg: "bg-orange-50 dark:bg-orange-950" },
  { key: "priority",  label: "Priority",  count: 5,  color: "text-red-700 dark:text-red-400",       bg: "bg-red-50 dark:bg-red-950" },
  { key: "sales",     label: "Sales",     count: 12, color: "text-cyan-700 dark:text-cyan-400",     bg: "bg-cyan-50 dark:bg-cyan-950" },
  { key: "support",   label: "Support",   count: 8,  color: "text-amber-700 dark:text-amber-400",   bg: "bg-amber-50 dark:bg-amber-950" },
];

export const GROUP_COLORS: Record<string, string> = {
  "Mumbai Traders":  "#537ff1",
  "Delhi Wholesale": "#b879ff",
  "Bangalore Tech":  "#1a8fa8",
  "Chennai Buyers":  "#1e9166",
  "Pune Factory":    "#c97200",
  "Jaipur Market":   "#ff6b6b",
  "Kolkata Dealers": "#328efa",
};

export const MESSAGES: Record<CategoryKey, Message[]> = {
  orders: [
    { id: 1,  time: "10:32 AM", group: "Mumbai Traders",  groupAvatar: "MT", groupColor: GROUP_COLORS["Mumbai Traders"],  sender: "Ankit Sharma",   text: "Please confirm order #4521 for 200 units.",      category: "orders" },
    { id: 2,  time: "10:45 AM", group: "Delhi Wholesale", groupAvatar: "DW", groupColor: GROUP_COLORS["Delhi Wholesale"], sender: "Priya Verma",    text: "Order #4522 — need delivery by Friday.",        category: "orders" },
    { id: 3,  time: "11:02 AM", group: "Bangalore Tech",  groupAvatar: "BT", groupColor: GROUP_COLORS["Bangalore Tech"],  sender: "Ravi Kumar",     text: "New bulk order request: 500 laptops, check.",   category: "orders" },
    { id: 4,  time: "11:20 AM", group: "Mumbai Traders",  groupAvatar: "MT", groupColor: GROUP_COLORS["Mumbai Traders"],  sender: "Sneha Patel",    text: "Can we split order into 3 shipments?",          category: "orders" },
    { id: 5,  time: "11:35 AM", group: "Pune Factory",    groupAvatar: "PF", groupColor: GROUP_COLORS["Pune Factory"],    sender: "Chirag Pandya",  text: "Order #4523 confirmed. Dispatch tomorrow.",     category: "orders" },
    { id: 6,  time: "12:00 PM", group: "Delhi Wholesale", groupAvatar: "DW", groupColor: GROUP_COLORS["Delhi Wholesale"], sender: "Mohit Joshi",    text: "Repeat order from last month — same quantity.", category: "orders" },
    { id: 7,  time: "12:15 PM", group: "Jaipur Market",   groupAvatar: "JM", groupColor: GROUP_COLORS["Jaipur Market"],   sender: "Farhan Sheikh",  text: "Rush order needed before weekend.",             category: "orders" },
    { id: 8,  time: "01:00 PM", group: "Bangalore Tech",  groupAvatar: "BT", groupColor: GROUP_COLORS["Bangalore Tech"],  sender: "Meena Pillai",   text: "Cancel order #4510 — client changed specs.",    category: "orders" },
    { id: 9,  time: "01:30 PM", group: "Kolkata Dealers", groupAvatar: "KD", groupColor: GROUP_COLORS["Kolkata Dealers"], sender: "Arjun Das",      text: "Order for 100 units — is stock available?",    category: "orders" },
    { id: 10, time: "02:10 PM", group: "Mumbai Traders",  groupAvatar: "MT", groupColor: GROUP_COLORS["Mumbai Traders"],  sender: "Kavita Singh",   text: "Reorder cycle for December confirmed.",         category: "orders" },
  ],
  payments: [
    { id: 11, time: "09:15 AM", group: "Mumbai Traders",  groupAvatar: "MT", groupColor: GROUP_COLORS["Mumbai Traders"],  sender: "Ankit Sharma",  text: "Payment of ₹45,000 cleared for order #4510.",   category: "payments" },
    { id: 12, time: "09:40 AM", group: "Delhi Wholesale", groupAvatar: "DW", groupColor: GROUP_COLORS["Delhi Wholesale"], sender: "Priya Verma",   text: "Pending payment ₹1.2L — please remind client.", category: "payments" },
    { id: 13, time: "10:05 AM", group: "Chennai Buyers",  groupAvatar: "CB", groupColor: GROUP_COLORS["Chennai Buyers"],  sender: "Lakshmi Iyer",  text: "Invoice #INV-2291 sent. Awaiting confirmation.", category: "payments" },
    { id: 14, time: "10:50 AM", group: "Pune Factory",    groupAvatar: "PF", groupColor: GROUP_COLORS["Pune Factory"],    sender: "Tanya Desai",   text: "Advance payment received for May batch.",        category: "payments" },
    { id: 15, time: "11:10 AM", group: "Kolkata Dealers", groupAvatar: "KD", groupColor: GROUP_COLORS["Kolkata Dealers"], sender: "Arjun Das",     text: "Refund request raised for damaged goods.",       category: "payments" },
    { id: 16, time: "12:30 PM", group: "Mumbai Traders",  groupAvatar: "MT", groupColor: GROUP_COLORS["Mumbai Traders"],  sender: "Deepak Gupta",  text: "Payment link shared. Deadline EOD.",             category: "payments" },
    { id: 17, time: "01:45 PM", group: "Bangalore Tech",  groupAvatar: "BT", groupColor: GROUP_COLORS["Bangalore Tech"],  sender: "Ravi Kumar",    text: "GST invoice needed urgently for payment.",       category: "payments" },
    { id: 18, time: "02:20 PM", group: "Jaipur Market",   groupAvatar: "JM", groupColor: GROUP_COLORS["Jaipur Market"],   sender: "Gurpreet Singh", text: "Credit note applied to next order.",            category: "payments" },
    { id: 19, time: "03:00 PM", group: "Delhi Wholesale", groupAvatar: "DW", groupColor: GROUP_COLORS["Delhi Wholesale"], sender: "Mohit Joshi",   text: "Partial payment ₹30K received, balance pending.", category: "payments" },
  ],
  inventory: [
    { id: 20, time: "08:30 AM", group: "Pune Factory",    groupAvatar: "PF", groupColor: GROUP_COLORS["Pune Factory"],    sender: "Chirag Pandya", text: "Stock count: 320 units remaining in warehouse.",  category: "inventory" },
    { id: 21, time: "09:00 AM", group: "Mumbai Traders",  groupAvatar: "MT", groupColor: GROUP_COLORS["Mumbai Traders"],  sender: "Ankit Sharma",  text: "Low stock alert: SKU-1021 below threshold.",     category: "inventory" },
    { id: 22, time: "09:45 AM", group: "Delhi Wholesale", groupAvatar: "DW", groupColor: GROUP_COLORS["Delhi Wholesale"], sender: "Priya Verma",   text: "New shipment arrived — 500 units added.",        category: "inventory" },
    { id: 23, time: "10:15 AM", group: "Bangalore Tech",  groupAvatar: "BT", groupColor: GROUP_COLORS["Bangalore Tech"],  sender: "Ravi Kumar",    text: "Request to hold 100 units for ongoing deal.",    category: "inventory" },
    { id: 24, time: "10:55 AM", group: "Kolkata Dealers", groupAvatar: "KD", groupColor: GROUP_COLORS["Kolkata Dealers"], sender: "Arjun Das",     text: "Check expiry on perishable batch 2024-B.",       category: "inventory" },
    { id: 25, time: "11:30 AM", group: "Chennai Buyers",  groupAvatar: "CB", groupColor: GROUP_COLORS["Chennai Buyers"],  sender: "Lakshmi Iyer",  text: "Transfer 50 units from Mumbai to Delhi store.",  category: "inventory" },
    { id: 26, time: "12:00 PM", group: "Jaipur Market",   groupAvatar: "JM", groupColor: GROUP_COLORS["Jaipur Market"],   sender: "Farhan Sheikh", text: "Restock request: SKU-2033 nearly depleted.",     category: "inventory" },
    { id: 27, time: "01:00 PM", group: "Pune Factory",    groupAvatar: "PF", groupColor: GROUP_COLORS["Pune Factory"],    sender: "Chirag Pandya", text: "Audit complete. 12 units discrepancy found.",    category: "inventory" },
    { id: 28, time: "01:50 PM", group: "Mumbai Traders",  groupAvatar: "MT", groupColor: GROUP_COLORS["Mumbai Traders"],  sender: "Kavita Singh",  text: "Reserve 200 units for Diwali campaign.",         category: "inventory" },
    { id: 29, time: "02:40 PM", group: "Delhi Wholesale", groupAvatar: "DW", groupColor: GROUP_COLORS["Delhi Wholesale"], sender: "Mohit Joshi",   text: "New SKU-3045 listed — update price list.",       category: "inventory" },
    { id: 30, time: "03:10 PM", group: "Bangalore Tech",  groupAvatar: "BT", groupColor: GROUP_COLORS["Bangalore Tech"],  sender: "Ravi Kumar",    text: "Damaged batch quarantined. Insurance claim filed.", category: "inventory" },
  ],
  logistics: [
    { id: 31, time: "07:45 AM", group: "Mumbai Traders",  groupAvatar: "MT", groupColor: GROUP_COLORS["Mumbai Traders"],  sender: "Ankit Sharma",  text: "Truck dispatch delayed — driver unavailable.",   category: "logistics" },
    { id: 32, time: "08:30 AM", group: "Pune Factory",    groupAvatar: "PF", groupColor: GROUP_COLORS["Pune Factory"],    sender: "Chirag Pandya", text: "Shipment #SH-891 out for delivery.",             category: "logistics" },
    { id: 33, time: "09:20 AM", group: "Delhi Wholesale", groupAvatar: "DW", groupColor: GROUP_COLORS["Delhi Wholesale"], sender: "Priya Verma",   text: "Customs clearance pending at Chennai port.",     category: "logistics" },
    { id: 34, time: "10:00 AM", group: "Kolkata Dealers", groupAvatar: "KD", groupColor: GROUP_COLORS["Kolkata Dealers"], sender: "Arjun Das",     text: "Delivery address updated for order #4508.",      category: "logistics" },
    { id: 35, time: "11:00 AM", group: "Jaipur Market",   groupAvatar: "JM", groupColor: GROUP_COLORS["Jaipur Market"],   sender: "Gurpreet Singh", text: "Last-mile delivery partner changed. ETA +2 days.", category: "logistics" },
    { id: 36, time: "12:10 PM", group: "Chennai Buyers",  groupAvatar: "CB", groupColor: GROUP_COLORS["Chennai Buyers"],  sender: "Lakshmi Iyer",  text: "Tracking link shared with customer.",            category: "logistics" },
    { id: 37, time: "01:30 PM", group: "Bangalore Tech",  groupAvatar: "BT", groupColor: GROUP_COLORS["Bangalore Tech"],  sender: "Ravi Kumar",    text: "Return pickup scheduled for tomorrow 10 AM.",    category: "logistics" },
  ],
  priority: [
    { id: 38, time: "08:00 AM", group: "Mumbai Traders",  groupAvatar: "MT", groupColor: GROUP_COLORS["Mumbai Traders"],  sender: "Ankit Sharma",  text: "URGENT: key client order stuck in processing.",   category: "priority" },
    { id: 39, time: "09:30 AM", group: "Delhi Wholesale", groupAvatar: "DW", groupColor: GROUP_COLORS["Delhi Wholesale"], sender: "Priya Verma",   text: "Escalation from VP: need update on order #4499.", category: "priority" },
    { id: 40, time: "10:20 AM", group: "Pune Factory",    groupAvatar: "PF", groupColor: GROUP_COLORS["Pune Factory"],    sender: "Chirag Pandya", text: "Machine breakdown — production halted.",          category: "priority" },
    { id: 41, time: "11:45 AM", group: "Bangalore Tech",  groupAvatar: "BT", groupColor: GROUP_COLORS["Bangalore Tech"],  sender: "Ravi Kumar",    text: "Critical bug in order system — dev team alerted.", category: "priority" },
    { id: 42, time: "01:00 PM", group: "Jaipur Market",   groupAvatar: "JM", groupColor: GROUP_COLORS["Jaipur Market"],   sender: "Farhan Sheikh", text: "Major client threatening to cancel — escalate.",   category: "priority" },
  ],
  sales: [
    { id: 43, time: "09:00 AM", group: "Mumbai Traders",  groupAvatar: "MT", groupColor: GROUP_COLORS["Mumbai Traders"],  sender: "Ankit Sharma",   text: "New lead from referral: Tata subsidiary contact.", category: "sales" },
    { id: 44, time: "09:30 AM", group: "Delhi Wholesale", groupAvatar: "DW", groupColor: GROUP_COLORS["Delhi Wholesale"], sender: "Priya Verma",    text: "Demo scheduled for Thursday 3 PM.",              category: "sales" },
    { id: 45, time: "10:10 AM", group: "Kolkata Dealers", groupAvatar: "KD", groupColor: GROUP_COLORS["Kolkata Dealers"], sender: "Arjun Das",      text: "Proposal sent to 3 new distributors.",           category: "sales" },
    { id: 46, time: "10:50 AM", group: "Chennai Buyers",  groupAvatar: "CB", groupColor: GROUP_COLORS["Chennai Buyers"],  sender: "Lakshmi Iyer",   text: "Follow-up on Q2 pipeline — 12 warm leads.",      category: "sales" },
    { id: 47, time: "11:20 AM", group: "Bangalore Tech",  groupAvatar: "BT", groupColor: GROUP_COLORS["Bangalore Tech"],  sender: "Ravi Kumar",     text: "Competitive pricing request from key account.",   category: "sales" },
    { id: 48, time: "12:00 PM", group: "Jaipur Market",   groupAvatar: "JM", groupColor: GROUP_COLORS["Jaipur Market"],   sender: "Gurpreet Singh", text: "Closed deal: ₹3.5L annual contract signed.",     category: "sales" },
    { id: 49, time: "01:00 PM", group: "Pune Factory",    groupAvatar: "PF", groupColor: GROUP_COLORS["Pune Factory"],    sender: "Tanya Desai",    text: "Upsell opportunity: client asked about add-ons.", category: "sales" },
    { id: 50, time: "02:00 PM", group: "Delhi Wholesale", groupAvatar: "DW", groupColor: GROUP_COLORS["Delhi Wholesale"], sender: "Mohit Joshi",    text: "Lost deal analysis — price was the blocker.",    category: "sales" },
    { id: 51, time: "02:30 PM", group: "Mumbai Traders",  groupAvatar: "MT", groupColor: GROUP_COLORS["Mumbai Traders"],  sender: "Kavita Singh",   text: "New inbound from Instagram ad campaign.",        category: "sales" },
    { id: 52, time: "03:15 PM", group: "Kolkata Dealers", groupAvatar: "KD", groupColor: GROUP_COLORS["Kolkata Dealers"], sender: "Arjun Das",      text: "Q3 forecast updated — 18% growth projected.",    category: "sales" },
    { id: 53, time: "04:00 PM", group: "Bangalore Tech",  groupAvatar: "BT", groupColor: GROUP_COLORS["Bangalore Tech"],  sender: "Ravi Kumar",     text: "Referral bonus activated for 2 new clients.",    category: "sales" },
    { id: 54, time: "04:30 PM", group: "Chennai Buyers",  groupAvatar: "CB", groupColor: GROUP_COLORS["Chennai Buyers"],  sender: "Lakshmi Iyer",   text: "Partnership proposal from competitor — evaluate.", category: "sales" },
  ],
  support: [
    { id: 55, time: "08:15 AM", group: "Mumbai Traders",  groupAvatar: "MT", groupColor: GROUP_COLORS["Mumbai Traders"],  sender: "Ankit Sharma",  text: "Customer complaint: wrong items delivered.",      category: "support" },
    { id: 56, time: "09:00 AM", group: "Delhi Wholesale", groupAvatar: "DW", groupColor: GROUP_COLORS["Delhi Wholesale"], sender: "Priya Verma",   text: "Support ticket #T-221 still open after 3 days.", category: "support" },
    { id: 57, time: "10:00 AM", group: "Pune Factory",    groupAvatar: "PF", groupColor: GROUP_COLORS["Pune Factory"],    sender: "Chirag Pandya", text: "Product recall notice issued — handle urgently.", category: "support" },
    { id: 58, time: "10:45 AM", group: "Kolkata Dealers", groupAvatar: "KD", groupColor: GROUP_COLORS["Kolkata Dealers"], sender: "Arjun Das",     text: "Replacement requested for broken unit.",         category: "support" },
    { id: 59, time: "11:30 AM", group: "Chennai Buyers",  groupAvatar: "CB", groupColor: GROUP_COLORS["Chennai Buyers"],  sender: "Lakshmi Iyer",  text: "Escalated complaint from premium customer.",     category: "support" },
    { id: 60, time: "12:00 PM", group: "Jaipur Market",   groupAvatar: "JM", groupColor: GROUP_COLORS["Jaipur Market"],   sender: "Farhan Sheikh", text: "FAQ document shared — reducing repeat queries.", category: "support" },
    { id: 61, time: "01:00 PM", group: "Bangalore Tech",  groupAvatar: "BT", groupColor: GROUP_COLORS["Bangalore Tech"],  sender: "Ravi Kumar",    text: "Live chat integration requested by client.",     category: "support" },
    { id: 62, time: "02:00 PM", group: "Mumbai Traders",  groupAvatar: "MT", groupColor: GROUP_COLORS["Mumbai Traders"],  sender: "Kavita Singh",  text: "Onboarding support session booked for Friday.",  category: "support" },
  ],
};

export const FLYOUT_HISTORY: Record<string, { from: string; text: string }[]> = {
  "Mumbai Traders":  [{ from: "Ankit",   text: "Hi team, need status update on pending orders." }, { from: "You", text: "Checking now, will revert shortly." }, { from: "Ankit",   text: "Thanks! Also flagged in the sheet." }],
  "Delhi Wholesale": [{ from: "Priya",   text: "New season catalog ready for review." },           { from: "You", text: "Shared the link in the drive." },          { from: "Priya",   text: "Got it, reviewing now." }],
  "Bangalore Tech":  [{ from: "Ravi",    text: "Server maintenance tonight 11 PM IST." },          { from: "You", text: "Noted. Will inform the team." },            { from: "Ravi",    text: "Please confirm once notified." }],
  "Chennai Buyers":  [{ from: "Lakshmi", text: "Dispatch for order 4499 done?" },                  { from: "You", text: "Yes, tracking link sent to client." },       { from: "Lakshmi", text: "Great, client confirmed." }],
  "Pune Factory":    [{ from: "Chirag",  text: "Production batch 12 cleared QC." },                { from: "You", text: "Good. Move to dispatch queue." },            { from: "Chirag",  text: "Done, ETA tomorrow morning." }],
  "Jaipur Market":   [{ from: "Farhan",  text: "New reseller agreement signed." },                  { from: "You", text: "Congratulations! Send docs to legal." },     { from: "Farhan",  text: "Already sent, awaiting review." }],
  "Kolkata Dealers": [{ from: "Arjun",   text: "Stock transfer request sent." },                   { from: "You", text: "Approved. Logistics notified." },            { from: "Arjun",   text: "Thanks, tracking shows in transit." }],
};
